baseURL = 'https://neale.dev'

title = "David Neale"
languageCode = "en-gb"
enableGitInfo = false

[params]
email = "david@neale.dev"
favicon = "img/logo.svg"
firstName = "David"
lastName = "Neale"
description = "A delivery-oriented technical strategist with extensive experience across software engineering, AWS, GCP, Kubernetes, and cybersecurity. Chief Architect at Admiral Money."
profileImage = "img/davidportrait.jpg"

[params.google]

[params.google.analytics]
trackerID = "G-CNYBLK0WJ0"

[outputs]
home = ["HTML"]

[markup.goldmark.renderer]
unsafe = true
